CREATE TABLE TB_USUARIO
(
	cod_usuario		INT IDENTITY(1,1),
	nomecompleto	VARCHAR(100),
	login			VARCHAR(10),
	senha			VARCHAR(100),
	status			int	DEFAULT 1
)
GO

ALTER TABLE TB_USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(cod_usuario)

CREATE TABLE TB_TAREFA
(
	cod_tarefa		INT IDENTITY(1,1),
	cod_usuario		INT,
	nome			VARCHAR(100),
	dataentrega		DATETIME,
	descricao		VARCHAR(100)
)

ALTER TABLE TB_TAREFA ADD CONSTRAINT PK_TAREFA PRIMARY KEY(cod_tarefa)
ALTER TABLE TB_TAREFA ADD CONSTRAINT FK_TAREFA_USUARIO FOREIGN KEY(cod_usuario) REFERENCES TB_USUARIO(cod_usuario)
GO